#!/bin/bash
"""
MIT License

Copyright (c) 2018 Kyle Dixler

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

child_process=$(read TERM_PID < <(xdotool getactivewindow getwindowpid) && ps --ppid "$TERM_PID" -o pid=); child_process=$(echo "$child_process" | tr -d ' ')
child_path=$(readlink -e "/proc/$child_process/cwd")
# child_name=$(< /proc/"$child_process"/status grep "Name:" | awk '{ print $2 }')
# child_cmd=$(< /proc/"$child_process"/cmdline tr '\000' ' ')

function find_ssh(){
   if [ "$1" = "" ]; then
      ret=""
      return 1
   fi
   proc_name=$(< /proc/"$1"/status grep '^Name:' | awk '{ print $2 }')
   if [ "$proc_name" = "ssh" ]; then
      ret="$1"
      return 0
   fi
   for child in $(cat /proc/"$1"/task/"$1"/children); do
      find_ssh "$child" || return 0
   done
}
find_ssh "$child_process" && echo "$ret"

baby_process="$ret"
# baby_path=$(readlink -e /proc/"$baby_process"/cwd)
baby_name=$(< /proc/"$baby_process"/status grep "Name:" | awk '{ print $2 }')
baby_cmd=$(< /proc/"$baby_process"/cmdline tr '\000' ' ')

if [ "$baby_name" = "ssh" ]; then
   xfce4-terminal --disable-server --working-directory="$child_path" --command="$SHELL -c \"$baby_cmd\""
else
   xfce4-terminal --disable-server --working-directory="$child_path"
fi
